### ISSUE TITLE
ReachedUpper/LowerLimit error

### ISSUE THREAD

**Issue by kennumen** [mezzodrinker/spas#13]
rev9 line 562:

These will always return true if no limits are set?

```
		public static bool ReachedLowerLimit(IMyMotorStator rotor) { return !HasLowerLimit(rotor) || (HasLowerLimit(rotor) && RotationEquals(ToDegrees(rotor.Angle), ToDegrees(rotor.LowerLimit))); }

		public static bool ReachedUpperLimit(IMyMotorStator rotor) { return !HasUpperLimit(rotor) || (HasUpperLimit(rotor) && RotationEquals(ToDegrees(rotor.Angle), ToDegrees(rotor.UpperLimit))); }

```
Let's work/simplify this out with some pseudo code. 

```
1. return NOT ( NOT rotor.HasNoLimit) OR ( NOT(rotor.HasNoLimit) AND rotor.limitReached);
2. return rotor.HasNoLimit OR (rotor.HasLimit AND rotor.limitReached);
// but if rotor.HasNoLimit is true, the limit can never be reached and should return false?

Solution:
		public static bool ReachedLowerLimit(IMyMotorStator rotor) { return (HasLowerLimit(rotor) && RotationEquals(ToDegrees(rotor.Angle), ToDegrees(rotor.LowerLimit))); }

		public static bool ReachedUpperLimit(IMyMotorStator rotor) { return (HasUpperLimit(rotor) && RotationEquals(ToDegrees(rotor.Angle), ToDegrees(rotor.UpperLimit))); }

```

**Comment by mezzodrinker** [comment]
If the limits were never reached, the script would continuously spin the solar panels while in hibernation mode and thus defeat the use of an hibernation mode.

**Comment by kennumen** [comment]
Oh I see. This works because you only call those two functions from Hibernate(). Going to reopen this issue (just once) as I clarified my position, though this is perhaps a case of author's choice.

I still feel they don't do as they're named, so for clarity I would still commit my changes and move the HasLimit checks to Hibernate. If you were ever to use ReachedUpper/LowerLimit in say Work->Status=ALIGNING those functions would act as expected.

Additional change: Work->Hibernate() line 455:
```
    void Hibernate()
    {
// <snip>
// old
                if (Utilities.ReachedLowerLimit(rotor) || Utilities.ReachedUpperLimit(rotor)) Utilities.ToggleOff(rotor);
// new
                if (Utilities.ReachedLowerLimit(rotor) || Utilities.ReachedUpperLimit(rotor) || !HasLowerLimit(rotor) || !HasUpperLimit(rotor)) Utilities.ToggleOff(rotor);
// <snip>
    }
```
This should actually even be a functional improvement in cases with a HasUpperLimit XOR HasLowerLimit where it moves to that limit. If you can even have just one limit on rotors in SE. Would actually be a rather clever way to setup starting position on a planet for the start of a new day.

**Comment by mezzodrinker** [comment]
> If you can even have just one limit on rotors in SE.

You actually can.

> This should actually even be a functional improvement in cases with a HasUpperLimit XOR HasLowerLimit where it moves to that limit. [...] Would actually be a rather clever way to setup starting position on a planet for the start of a new day.

That might be a good idea indeed. But the code you provided would cause the rotors to be toggled off if they have no lower limit, no upper limit or neither, no matter if the respective limits have been reached.

Also, since there's no API or anything for in-game scripts (not for them to use but for them to provide) and (apparently) almost no one cares about the code (I'd probably have more forks if that wasn't the case), I could (if I wanted to) name the two functions `DoSomething` and `DoSomethingDifferently`.

**Comment by mezzodrinker** [comment]
And I have now found out that there was two `!` in your code. Sorry about that.

**Comment by kennumen** [comment]
*notices you're still leaving this issue closed despite clearly listing several bugs including fixes*

So I applied these fixes having switched to a 2rotor system on my station. So far it acts very strangely for 2-5 minutes then does swimmingly. Once it reaches Hibernate it spasms around 0 degrees on the rotor with limits from -90 to 90 (I'm on a planet, half a sphere is all I need/want). Another error in your code:

Hibernate (line 445ish)
```
                if (Utilities.ReachedLowerLimit(rotor) || Utilities.ReachedUpperLimit(rotor) || (!Utilities.HasLowerLimit(rotor) && !Utilities.HasUpperLimit(rotor))) Utilities.ToggleOff(rotor);
                else {
                    float distanceFromUpperLimit = rotor.UpperLimit - rotor.Angle;
                    float distanceFromLowerLimit = rotor.Angle - rotor.LowerLimit;

                    Utilities.ToggleOn(rotor);
// old, conditional reversed (moves towards furthest away, never reaching either):
//                    if (distanceFromLowerLimit < distanceFromUpperLimit) Utilities.RotateTowards(rotor, Utilities.ToDegrees(rotor.UpperLimit), speed);
// new:                     if (distanceFromLowerLimit > distanceFromUpperLimit) Utilities.RotateTowards(rotor, Utilities.ToDegrees(rotor.UpperLimit), speed);
                    else Utilities.RotateTowards(rotor, Utilities.ToDegrees(rotor.LowerLimit), speed);

                    idle = false;
                }
```

Furthermore I feel it's more logical if both limits are present to hibernate in the middle, so I'm currently using the following function which appears to work exactly as intended:
```
    void Hibernate()
    {
        bool idle = true;
        float speed = GetRotorSpeed();
        for (int i = 0; i < rotors.Count; i++)
        {
            List<IMyMotorStator> axis = rotors[i];
            for (int j = 0; j < axis.Count; j++)
            {
                IMyMotorStator rotor = axis[j];
                if ((!Utilities.HasUpperLimit(rotor) && Utilities.ReachedLowerLimit(rotor)) || (Utilities.HasLowerLimit(rotor) && Utilities.ReachedUpperLimit(rotor)) || (!Utilities.HasLowerLimit(rotor) && !Utilities.HasUpperLimit(rotor))) Utilities.ToggleOff(rotor);
                else if (Utilities.HasLowerLimit(rotor) && Utilities.HasUpperLimit(rotor)) {
                    float centerLimitAngle = rotor.UpperLimit - rotor.LowerLimit;

                    if (Math.Abs(centerLimitAngle - rotor.Angle) < 5) // close enough, rounding error
                    {
                        Utilities.ToggleOff(rotor);
                    }
                    else
                    {
                        Utilities.ToggleOn(rotor);
                        Utilities.RotateTowards(rotor, Utilities.ToDegrees(centerLimitAngle), speed);
                        idle = false;
                    }
                }
                else {
                    float distanceFromUpperLimit = rotor.UpperLimit - rotor.Angle;
                    float distanceFromLowerLimit = rotor.Angle - rotor.LowerLimit;

                    Utilities.ToggleOn(rotor);
                    if (distanceFromLowerLimit < distanceFromUpperLimit) Utilities.RotateTowards(rotor, Utilities.ToDegrees(rotor.UpperLimit), speed);
                    else Utilities.RotateTowards(rotor, Utilities.ToDegrees(rotor.LowerLimit), speed);

                    idle = false;
                }
            }
        }
        UpdateNames();
        currentStatus = Status.HIBERNATING;
        Utilities.Trigger(timer, idle ? Configuration.Features.EnergySaver.HibernationIdleDelay : Configuration.Features.EnergySaver.HibernationWorkDelay);
    }
```

**Comment by mezzodrinker** [comment]
About the error in `Hibernate()`, yes, I noticed that as well and (on my local version) it looks like this:
```c#
void Hibernate() {
	bool idle = true;
	float speed = GetRotorSpeed();
	for (int i = 0; i < rotors.Count; i++) {
		List<IMyMotorStator> axis = rotors[i];
		for (int j = 0; j < axis.Count; j++) {
			IMyMotorStator rotor = axis[j];
			if (Utilities.ReachedLowerLimit(rotor) || Utilities.ReachedUpperLimit(rotor)) Utilities.ToggleOff(rotor);
			else {
				idle = false;
				if (currentStatus != Status.HIBERNATE) {
					float distanceFromUpperLimit = rotor.UpperLimit - rotor.Angle;
					float distanceFromLowerLimit = rotor.Angle - rotor.LowerLimit;

					Utilities.ToggleOn(rotor);
					if (distanceFromLowerLimit < distanceFromUpperLimit) Utilities.RotateTowards(rotor, Utilities.ToDegrees(rotor.UpperLimit), speed);
					else Utilities.RotateTowards(rotor, Utilities.ToDegrees(rotor.LowerLimit), speed);
				}
			}
		}
	}
	UpdateNames();
	currentStatus = Status.HIBERNATE;
	Utilities.Trigger(timer, idle ? Configuration.Features.EnergySaver.HibernationIdleDelay : Configuration.Features.EnergySaver.HibernationWorkDelay);
}
```
With the small addition of...
```c#
if (currentStatus != Status.HIBERNATE)
```
...the script searches for the furthest limit from the current position as soon as it switches into hibernation mode but after that, it only checks whether said limit has been reached or not.

That being said, I am currently rewriting rev9 completely. I spent quite a while thinking about how I could improve the algorithm, worked out a sequence diagram and am now tinkering with the code to find out how to implement it in the most accurate way. It looks like the "revamped" rev9 will look quite a bit different and will (probably) have less/different configuration options.

If you wish to take part in verifying that my code is working, I'll commit my changes as soon as I notice your reply. Also, you're always free to fork the repository.

**Comment by kennumen** [comment]
rev9 as is now mostly works with 2 rotors. Knowing you're doing a full rewrite I'll stick with that and wait until you've fleshed out your new version a bit more. I'd prefer not to test until it does better than a static (1 rotor) rotation. I also play SE in bursts (the amount of bugs cause me to ragequit every few weeks).

I'll leave you to your full rewrite, feel free to ask if you would like me to do a quick lookover. Also, apologies for not learning proper git and doing pull requests.
