### ISSUE TITLE
rev8 SPAS is spastic yet lazy

### ISSUE THREAD

**Issue by kennumen** [mezzodrinker/spas#14]
Running steam workship rev8.

First off I love this mod. Made a hardcore start and spent at least an hour debugging this code in-game while to save my batteries from, well, me.

Situation:
Earth (120 minutes per day / sun loop), not equator but not pole (snow, mountains, clear sight to sun entire day), small ship vanilla panels vertically placed (better at 10 and 14 than noon) on single advanced rotor. SPAS solar panel is the center of 9 panels. Peak max appears to be sub 25 kW though I didn't sit there for an hour just to check.

Problem:
Script (very) occasionally looks like it's working but vast majority of time it runs away from the sun. Just not directly. You can clearly see the pattern where it takes 2 steps wrong and 1 step correct (hence SPAStic - pun intended), almost like it's working with outdated data from the last loop or some such. Changing config variables appears to do little. Changed work step from default 2.0f to 1.0f (recommended: 1.5f - 2.5f) still makes it wrong but it's 2 OR 3 steps wrong and 1 step correct. This continues until it reaches hibernate status (hence lazy) because SPAS turned them in-line to the sun instead of facing it.

Ironically (if my math is right) my best solution now is to turn off SPAS, get the solar panel at more or less optimal and (with a 120 minute day, half a rotation by day and half by night) set my rotation static at 0.0083 (should be 1/120 = 0.008333...) with an error of 0.4% means I have to reset it about every 30 (real life) hours to keep the error under 22.5 degrees. Surprisingly little maintenance but not automated and certainly less cool.

**Comment by kennumen** [comment]
Apologies, looks to be clone of issue #9 solved with rev9. Let me go figure out how to add custom mods (aka SPAS rev9) and get back to you.

**Comment by kennumen** [comment]
Nope, grabbed a fresh rev9, changed config variables, added LCD display (nice!) but still running away from the sun at a "2 steps worse, 1 step better" pattern.

**Comment by mezzodrinker** [comment]
Improvement of the alignment algorithm is the whole point of #11.
