### ISSUE TITLE
New parameters for morning position

### ISSUE THREAD

**Issue by Brelys** [mezzodrinker/spas#4]
Hello,
Maybe you could create a new list with the rotor angles that should be targetted during hibernation. That way you enter good approximate values for the sunrise and the solar panels will wait there.

By the way I love your script, it's really useful.

Sébastien

**Comment by mezzodrinker** [comment]
Hmm. That sure does sound like a viable alternative to what I was planning. Though it does need more and preciser input from the users' side, thus making configuration more complex. I'm not too sure what to think of your idea yet, let alone if I will add it, but I'll definitely keep it in mind!

**Comment by mezzodrinker** [comment]
This can now (since 6ec3c5d472da22c5d4a9f245993a0a0d5f056ad0) be achieved by setting the rotor's lower/upper limit. Once the script switches into hibernation mode, it will automatically rotate towards the furthest limit. For example:

> Lower limit = 50°
> Upper limit = 360°
> Current rotation = 55°
> In this case, the script will rotate the rotor towards the upper limit.
